<a href="https://colab.research.google.com/github/lisatwyw/epi-galla.github.io/blob/main/1st_bivariate_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# Part 1: Demo



# 1) Constructing data matrix




In [ ]:
(weight_height <-c(1,	182.9,		78.5,
2,	172.7,		60.8,
3,	175.3,		68.0,
4,	172.7,		65.8,
5,	160.0,		52.2,
6,	165.1,		54.4,	
7,	172.7,		60.3,
8,	162.6,		52.2)	)

tmp <-matrix( weight_height, 3) 

# c concatenate
# t transpose 

weight_height<-t(tmp)

(colnames(weight_height) <- c('id', 'height','weight'))

weight_height <- data.frame( weight_height)


[1]   1.0 182.9  78.5   2.0 172.7  60.8   3.0 175.3  68.0   4.0 172.7  65.8
[13]   5.0 160.0  52.2   6.0 165.1  54.4   7.0 172.7  60.3   8.0 162.6  52.2

[1] "id"     "height" "weight"

In [ ]:
weight_height

id height weight
1 1  182.9  78.5  
2 2  172.7  60.8  
3 3  175.3  68.0  
4 4  172.7  65.8  
5 5  160.0  52.2  
6 6  165.1  54.4  
7 7  172.7  60.3  
8 8  162.6  52.2

In [ ]:
ht_wt_data<-c(1, 182.9,		78.5,
2,	172.7,		60.8,
3,	175.3,		68.0,
4,	172.7,		65.8,
5,	160.0,		52.2,
6,	165.1,		54.4,	
7,	172.7,		60.3,
8,	162.6,		52.2)	

ht_wt_data<-matrix(ht_wt_data, 3) 
ht_wt_data


[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8] 
[1,]   1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0
[2,] 182.9 172.7 175.3 172.7 160.0 165.1 172.7 162.6
[3,]  78.5  60.8  68.0  65.8  52.2  54.4  60.3  52.2

In [ ]:
# to transpose, use the "t" function 

ht_wt_data<-t( ht_wt_data )
ht_wt_data 

[,1] [,2]  [,3]
[1,] 1    182.9 78.5
[2,] 2    172.7 60.8
[3,] 3    175.3 68.0
[4,] 4    172.7 65.8
[5,] 5    160.0 52.2
[6,] 6    165.1 54.4
[7,] 7    172.7 60.3
[8,] 8    162.6 52.2

Give values to the headers of our data matrix

In [ ]:
colnames( ht_wt_data ) <- c("sample_id", "height_cm", "weight_kg")
ht_wt_data


sample_id height_cm weight_kg
[1,] 1         182.9     78.5     
[2,] 2         172.7     60.8     
[3,] 3         175.3     68.0     
[4,] 4         172.7     65.8     
[5,] 5         160.0     52.2     
[6,] 6         165.1     54.4     
[7,] 7         172.7     60.3     
[8,] 8         162.6     52.2

# 2) Create a dataframe

In [ ]:
rownames( ht_wt_data ) <- 1:8
ht_wt_data<-data.frame( ht_wt_data  )
ht_wt_data

sample_id height_cm weight_kg
1 1         182.9     78.5     
2 2         172.7     60.8     
3 3         175.3     68.0     
4 4         172.7     65.8     
5 5         160.0     52.2     
6 6         165.1     54.4     
7 7         172.7     60.3     
8 8         162.6     52.2

In [ ]:
ht_wt_data$height_cm
 

[1] 182.9 172.7 175.3 172.7 160.0 165.1 172.7 162.6

In [ ]:
h <- ht_wt_data$height_cm
w <- ht_wt_data$weight_kg

x_mean <- sum( h )/ length(h)
x_mean

[1] 170.5

In [ ]:
mean( h )

[1] 170.5

In [ ]:
y_mean<-mean( w ) 
y_mean 

[1] 61.525

# 3) Calculate ```b``` via a closed-form solution

In [ ]:
numerator<- sum( (h - x_mean)* (w-y_mean ) )
numerator

[1] 456.74

In [ ]:
denominator <-sum( (h- x_mean )**2 )
denominator


[1] 393.14

In [ ]:
b <- numerator/ denominator
b

[1] 1.161774

In [ ]:
b0 <- y_mean - b*x_mean 
b0

[1] -136.5575

# 4) Data fit via linear model ```lm()```

In [ ]:
# regress/predict Y on X:

y_on_x_mdl <- lm(ht_wt_data$weight_kg ~ ht_wt_data$height_cm )
y_on_x_mdl 



Call:
lm(formula = ht_wt_data$weight_kg ~ ht_wt_data$height_cm)

Coefficients:
         (Intercept)  ht_wt_data$height_cm  
            -136.558                 1.162  


In [ ]:
# regress/predict X on Y
x_on_y_mdl <- lm(ht_wt_data$height_cm ~ ht_wt_data$weight_kg  )
x_on_y_mdl  


Call:
lm(formula = ht_wt_data$height_cm ~ ht_wt_data$weight_kg)

Coefficients:
         (Intercept)  ht_wt_data$weight_kg  
            121.6335                0.7943  


In [ ]:
typeof(x_on_y_mdl)  

[1] "list"

In [ ]:
typeof( x_on_y_mdl[1] )

[1] "list"

In [ ]:
bprime<-x_on_y_mdl[1]$coefficients[2]
bprime

ht_wt_data$weight_kg 
           0.7942545

In [ ]:
typeof(bprime)


[1] "double"

In [ ]:
b<-y_on_x_mdl[1]$coefficients[2]

In [ ]:
r_square <- b*bprime
r = sqrt( r_square )
r

ht_wt_data$height_cm 
           0.9605959

# Part 2: Check-in exercise 

Replicate the process using a different dataset:

|Height (cm) |FEV1 (litres) |
|--|--|
| 164|3.54|
|167|3.54|
|170.4|3.19|
|171.2|2.85|
|171.2|3.42|
|171.3|3.20|
|172.0|3.6|
|172|3.78|
|174|4.32|
|176|3.75|
|177|3.09|
|177|4.05|
|177|5.43|
|177.4|3.6|
|178|2.98|
|180.7|4.8|
|181|3.96|
|183.1|4.78|
|183.6|4.56|
|183.7|4.68|





In [ ]:
fev1_ht_df<-matrix( c(164, 	3.54,
167 ,	3.54,
170.4, 	3.19,
171.2, 	2.85,
171.2, 	3.42,
171.3, 	3.20,
172.0, 	3.6,
172, 	3.78,
174, 	4.32,
176, 	3.75,
177, 	3.09,
177, 	4.05,
177, 	5.43,
177.4, 	3.6,
178, 	2.98,
180.7, 	4.8,
181, 	3.96,
183.1, 	4.78,
183.6, 	4.56,
183.7, 	4.68), 2)


fev1_ht_df
dim(fev1_ht_df)

[,1]   [,2]   [,3]   [,4]   [,5]   [,6]  [,7]  [,8]   [,9]   [,10]  [,11] 
[1,] 164.00 167.00 170.40 171.20 171.20 171.3 172.0 172.00 174.00 176.00 177.00
[2,]   3.54   3.54   3.19   2.85   3.42   3.2   3.6   3.78   4.32   3.75   3.09
     [,12]  [,13]  [,14] [,15]  [,16] [,17]  [,18]  [,19]  [,20] 
[1,] 177.00 177.00 177.4 178.00 180.7 181.00 183.10 183.60 183.70
[2,]   4.05   5.43   3.6   2.98   4.8   3.96   4.78   4.56   4.68

[1]  2 20

In [ ]:
# let's suppose we have subject IDs  
sid <-seq( 1201, 1240, by=2) 
sid 
length(sid)

[1] 1201 1203 1205 1207 1209 1211 1213 1215 1217 1219 1221 1223 1225 1227 1229
[16] 1231 1233 1235 1237 1239

[1] 20

In [ ]:
# bind the rows using rbind
fev1_ht_df<-rbind( sid, fev1_ht_df)
fev1_ht_df

[,1]    [,2]    [,3]    [,4]    [,5]    [,6]   [,7]   [,8]    [,9]   
sid 1201.00 1203.00 1205.00 1207.00 1209.00 1211.0 1213.0 1215.00 1217.00
     164.00  167.00  170.40  171.20  171.20  171.3  172.0  172.00  174.00
       3.54    3.54    3.19    2.85    3.42    3.2    3.6    3.78    4.32
    [,10]   [,11]   [,12]   [,13]   [,14]  [,15]   [,16]  [,17]   [,18]  
sid 1219.00 1221.00 1223.00 1225.00 1227.0 1229.00 1231.0 1233.00 1235.00
     176.00  177.00  177.00  177.00  177.4  178.00  180.7  181.00  183.10
       3.75    3.09    4.05    5.43    3.6    2.98    4.8    3.96    4.78
    [,19]   [,20]  
sid 1237.00 1239.00
     183.60  183.70
       4.56    4.68

In [ ]:
# transpose
fev1_ht_df <- t(fev1_ht_df)
fev1_ht_df

sid            
 [1,] 1201 164.0 3.54
 [2,] 1203 167.0 3.54
 [3,] 1205 170.4 3.19
 [4,] 1207 171.2 2.85
 [5,] 1209 171.2 3.42
 [6,] 1211 171.3 3.20
 [7,] 1213 172.0 3.60
 [8,] 1215 172.0 3.78
 [9,] 1217 174.0 4.32
[10,] 1219 176.0 3.75
[11,] 1221 177.0 3.09
[12,] 1223 177.0 4.05
[13,] 1225 177.0 5.43
[14,] 1227 177.4 3.60
[15,] 1229 178.0 2.98
[16,] 1231 180.7 4.80
[17,] 1233 181.0 3.96
[18,] 1235 183.1 4.78
[19,] 1237 183.6 4.56
[20,] 1239 183.7 4.68

# 1) Create a data frame using the binded data

In [ ]:

fev1_ht_df <- data.frame(fev1_ht_df)
fev1_ht_df


sid  V2    V3  
1  1201 164.0 3.54
2  1203 167.0 3.54
3  1205 170.4 3.19
4  1207 171.2 2.85
5  1209 171.2 3.42
6  1211 171.3 3.20
7  1213 172.0 3.60
8  1215 172.0 3.78
9  1217 174.0 4.32
10 1219 176.0 3.75
11 1221 177.0 3.09
12 1223 177.0 4.05
13 1225 177.0 5.43
14 1227 177.4 3.60
15 1229 178.0 2.98
16 1231 180.7 4.80
17 1233 181.0 3.96
18 1235 183.1 4.78
19 1237 183.6 4.56
20 1239 183.7 4.68

In [ ]:
# transpose works for 3D
colnames(fev1_ht_df)<-c("sid","Height", "FEV1" )

fev1_ht_df

sid  Height FEV1
1  1201 164.0  3.54
2  1203 167.0  3.54
3  1205 170.4  3.19
4  1207 171.2  2.85
5  1209 171.2  3.42
6  1211 171.3  3.20
7  1213 172.0  3.60
8  1215 172.0  3.78
9  1217 174.0  4.32
10 1219 176.0  3.75
11 1221 177.0  3.09
12 1223 177.0  4.05
13 1225 177.0  5.43
14 1227 177.4  3.60
15 1229 178.0  2.98
16 1231 180.7  4.80
17 1233 181.0  3.96
18 1235 183.1  4.78
19 1237 183.6  4.56
20 1239 183.7  4.68

In [ ]:
x_on_y_mdl <- lm(fev1_ht_df$Height ~ fev1_ht_df$FEV1 )
y_on_x_mdl <- lm(fev1_ht_df$FEV1 ~  fev1_ht_df$Height  )


In [ ]:
b0 <- coef(summary(y_on_x_mdl))[1]
b  <- coef(summary(y_on_x_mdl))[2]

b0prime <- coef(summary(x_on_y_mdl))[1]
bprime  <- coef(summary(x_on_y_mdl))[2]

bprime
b

[1] 4.542415

[1] 0.07438926

In [ ]:
typeof(b)

[1] "double"

In [ ]:
r_square <- b*bprime 
r_square

r<- sqrt(r_square)
r

[1] 0.3379069

[1] 0.5812976

# 2) Interpret the output

In [ ]:
summary( y_on_x_mdl )


Call:
lm(formula = fev1_ht_df$FEV1 ~ fev1_ht_df$Height)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.07090 -0.32367  0.03446  0.31797  1.45349 

Coefficients:
                  Estimate Std. Error t value Pr(>|t|)   
(Intercept)       -9.19039    4.30644  -2.134  0.04684 * 
fev1_ht_df$Height  0.07439    0.02454   3.031  0.00719 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.5892 on 18 degrees of freedom
Multiple R-squared:  0.3379,	Adjusted R-squared:  0.3011 
F-statistic: 9.187 on 1 and 18 DF,  p-value: 0.007185


In [ ]:
xi <-c(fev1_ht_df$Height)
yi <-c(fev1_ht_df$FEV1)
x_mean <- mean( xi )
n <- length( xi )
y_mean = mean( yi )
residual_var <- 1/(n-2)*(sum(( yi - y_mean )**2) - b**2 *sum( (xi-x_mean)**2 ) ) 
ss_x <- sum( (xi-x_mean)^2)
se_b <- sqrt( residual_var /ss_x )
se_b
t <- b/se_b
t 
# Pr( >|t| )=.00719 tells us to reject null hypothesis that there's no association

[1] 0.02454342

[1] 3.030925

Predict FEV1 given height = 177cm

In [ ]:
x1=177

predicted_fev1 <- b0 + b * x1
print( predicted_fev1 )


[1] 3.976511


In [ ]:
delta <-(x1-x_mean)**2
se<- sqrt(residual_var *(1/n + delta/ss_x ))
se
val <-2.1
lower<-predicted_fev1 - val * se 
upper<-predicted_fev1 + val * se
o <-sprintf('Person with height %.2fcm is predicted to have FEV1 of %.2f liters with 95%% c.i. in [%.2f, %.2f]', x1, predicted_fev1, lower, upper)

print(o )


[1] 0.1376227

[1] "Person with height 177.00cm is predicted to have FEV1 of 3.98 liters with 95% c.i. in [3.69, 4.27]"


# 3) Example of defining own function ...and then calling it

In [ ]:
predict_fev1 <- function(x1, x_mean, residual_var, delta, ss_x)
{
  delta <-(x1-x_mean)**2
  se<- sqrt(residual_var *(1/n + delta/ss_x ))
  se
  val <-2.1
  lower<-predicted_fev1 - val * se 
  upper<-predicted_fev1 + val * se
  o <-sprintf('Person with height %.1fcm is predicted to have FEV1 of %.2f liters with 95%% c.i. in [%.2f, %.2f]', x1, predicted_fev1, lower, upper)

  print(o )
}

predict_fev1( xi[1], x_mean, residual_var, delta, ss_x)


[1] "Person with height 164.0cm is predicted to have FEV1 of 3.98 liters with 95% c.i. in [3.33, 4.63]"
